### ISSUE TITLE
Why not having the crate name "font_catcher" and then the binary be "font-catcher"?

### ISSUE THREAD

**Issue by cdecompilador** [GustavoPeredo/Font-Catcher#9]
It's weird to have to consume the library with a 
```rust
use font-catcher as font_catcher;
```
Renaming the crate to `font_catcher` but then in the `Cargo.toml` adding
a simple, the installed binary would be the same but the consuming library would be `font_catcher`:
```toml
[[bin]]
name = "font-catcher"
path   = "src/main.rs"
```
